# Generated by Django 4.1.3 on 2022-12-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.IntegerField(db_column='AdminID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.CharField(db_column='CategoryID', max_length=4, primary_key=True, serialize=False)),
                ('cname', models.CharField(db_column='CName', max_length=45)),
                ('cdescription', models.CharField(db_column='CDescription', max_length=200)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('corderid', models.CharField(db_column='cOrderID', max_length=255, primary_key=True, serialize=False)),
                ('citemid', models.CharField(db_column='cItemID', max_length=255)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'contain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cusratingid', models.CharField(db_column='cusRatingID', max_length=255)),
                ('cid', models.CharField(db_column='cID', max_length=255, primary_key=True, serialize=False)),
                ('failedorder', models.IntegerField(blank=True, db_column='failedOrder', null=True)),
                ('pendingorder', models.IntegerField(blank=True, db_column='pendingOrder', null=True)),
                ('successorder', models.IntegerField(blank=True, db_column='successOrder', null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('gasampleid', models.CharField(db_column='gaSampleID', max_length=255, primary_key=True, serialize=False)),
                ('gaitemid', models.CharField(db_column='gaItemID', max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'giveaway',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.CharField(db_column='ItemID', max_length=4, primary_key=True, serialize=False)),
                ('icategoryid', models.CharField(db_column='ICategoryID', max_length=4)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('idescription', models.CharField(db_column='IDescription', max_length=200)),
                ('itemlocation', models.CharField(db_column='ItemLocation', max_length=45)),
                ('price', models.IntegerField(db_column='Price')),
                ('itemimage', models.TextField(blank=True, db_column='ItemImage', null=True)),
                ('brand', models.CharField(db_column='Brand', max_length=45)),
                ('stock', models.IntegerField(db_column='Stock')),
                ('comment', models.CharField(blank=True, db_column='Comment', max_length=200, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.CharField(db_column='orderID', max_length=255, primary_key=True, serialize=False)),
                ('cid', models.IntegerField(db_column='cID')),
                ('senddate', models.CharField(blank=True, db_column='sendDate', max_length=255, null=True)),
                ('nodelivered', models.IntegerField(blank=True, db_column='noDelivered', null=True)),
                ('expecteddeliverydate', models.DateTimeField(blank=True, db_column='expectedDeliveryDate', null=True)),
                ('olocation', models.CharField(blank=True, db_column='oLocation', max_length=255, null=True)),
                ('cash', models.IntegerField(blank=True, null=True)),
                ('card', models.IntegerField(blank=True, null=True)),
                ('totalpayment', models.IntegerField(blank=True, db_column='totalPayment', null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stripe_token', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'order_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderOrderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'order_orderitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotionid', models.CharField(db_column='promotionID', max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('pname', models.CharField(blank=True, db_column='pName', max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('begintime', models.DateTimeField(blank=True, db_column='beginTime', null=True)),
                ('endtime', models.CharField(blank=True, db_column='endTime', max_length=45, null=True)),
            ],
            options={
                'db_table': 'promotion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingid', models.CharField(db_column='ratingID', max_length=255, primary_key=True, serialize=False)),
                ('ritemid', models.CharField(blank=True, db_column='rItemID', max_length=255, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sampleid', models.CharField(db_column='sampleID', max_length=255, primary_key=True, serialize=False)),
                ('promotionid', models.CharField(db_column='promotionID', max_length=255)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sample',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('sid', models.IntegerField(db_column='sID', primary_key=True, serialize=False)),
                ('vehicletype', models.CharField(blank=True, db_column='vehicleType', max_length=255, null=True)),
                ('licenseplate', models.CharField(blank=True, db_column='licensePlate', max_length=255, null=True)),
                ('shippername', models.CharField(blank=True, db_column='shipperName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'shipper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(db_column='UserID', primary_key=True, serialize=False)),
                ('phone', models.CharField(db_column='Phone', max_length=15)),
                ('username', models.CharField(db_column='UserName', max_length=255)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('userfname', models.CharField(db_column='UserFName', max_length=255)),
                ('userlnname', models.CharField(db_column='UserLNname', max_length=255)),
                ('city', models.CharField(db_column='City', max_length=255)),
                ('address1', models.CharField(db_column='Address1', max_length=255)),
                ('address2', models.CharField(blank=True, db_column='Address2', max_length=255, null=True)),
                ('postalcode', models.CharField(db_column='PostalCode', max_length=255)),
                ('country', models.CharField(db_column='Country', max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('vpromotionid', models.CharField(db_column='vPromotionID', max_length=255, primary_key=True, serialize=False)),
                ('vouchercode', models.CharField(db_column='voucherCode', max_length=255)),
                ('vname', models.CharField(blank=True, db_column='vName', max_length=45, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('expireddate', models.DateTimeField(blank=True, db_column='expiredDate', null=True)),
                ('validactive', models.IntegerField(blank=True, db_column='validActive', null=True)),
                ('moneydiscount', models.IntegerField(blank=True, db_column='moneyDiscount', null=True)),
            ],
            options={
                'db_table': 'voucher',
                'managed': False,
            },
        ),
    ]
